### PR TITLE
feat: add securityContext for initContainers

### PR DESCRIPTION
**Pull request by FelixKampfer**
## Description
This change sets a default securityContext for initContainers. This is useful because some admission controllers reject containers with no securityContext. 
An alternative implementation could see `scanJob.podTemplateSecurityContext` being passed to pkg/plugins/trivy/plugin.go's `GetScanJobSpec`, but I thought this might be simpler.

## Related issues
- Improves #121 

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [X] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [X] I've added usage information (if the PR introduces new options)
- [X] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@FelixKampfer thank you for the contribution, I wonder if it is worth making it configurable with default values set (as proposed). Allowing users the ability to overwrite values , wdyt ?

**Comment by FelixKampfer** [comment]
What about [the hardcoded securityContext of the scan containers](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L679)? What would happen to the current hardcoded value?

Could I make these configurable with the same property key? 
E.g.   `scanJobPodTemplateContainerSecurityContext`, so that the existing `scanJobPodTemplateSecurityContext` doesn't need to be modified.

**Comment by chen-keinan** [comment]
@FelixKampfer do we need this PR after merging #477 ?

**Comment by FelixKampfer** [comment]
No we do not, thanks!

**Pull request closed without merging**
