### PR TITLE
chore: support storageClassName for trivy-server statefulset

### LINKED ISSUE #854: Helm Chart should allow specification of trivy server storage class
Currently the StatefulSet storageClass section is empty, which is fine if there is a default storage class.  In our environment on a new cluster trivy might get installed before the CSI gets installed at which point there is no default storage class.  It would be better to allow this to be specified as a value (defaulting to blank).

I would suggest this be called out as value trivyServer.storageClassName, meaning create a new section in values for trivyServer, containing settings that only affect the trivyServer deployment.  The current trivyServer-related values are also consumed by the operator (e.g. healthcacheexpiration, trivyserverservice) so they are probably fine staying where they are.

### PR DESCRIPTION
**Pull request by MaxFedotov**
## Description

Add support for storageClassName param for trivy-server statefulset

## Related issues
- Close #854 

Remove this section if you don't have related PRs.

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [X] I've added tests that prove my fix is effective or that my feature works.
- [X] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [X] I've added usage information (if the PR introduces new options)
- [X] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by fengshunli — APPROVED** [review]
LGTM

**Comment by chen-keinan** [comment]
@MaxFedotov thank you for the contribution. could you please update docs ( [trivy](https://github.com/aquasecurity/trivy-operator/blob/main/docs/docs/vulnerability-scanning/trivy.md) and [helm](https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm) )

**Comment by fengshunli** [comment]
> @MaxFedotov thank you for the contribution. could you please update docs ( [trivy](https://github.com/aquasecurity/trivy-operator/blob/main/docs/docs/vulnerability-scanning/trivy.md) and [helm](https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm) ) 

I'll deal with it tomorrow

**Comment by chen-keinan** [comment]
> > @MaxFedotov thank you for the contribution. could you please update docs ( [trivy](https://github.com/aquasecurity/trivy-operator/blob/main/docs/docs/vulnerability-scanning/trivy.md) and [helm](https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm) )
> 
> I'll deal with it tomorrow @chen-keinan

It should be included as part of this PR  @MaxFedotov

**Comment by MaxFedotov** [comment]
@chen-keinan ok, will add it.

@fengshunli i've also found out that `trivy-server` uses [serviceAccountName: trivy-operator](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/trivy-server.yaml#L58). But this service account is not created by helm. Is it ok if I will add it in the same PR?

**Comment by chen-keinan** [comment]
> @chen-keinan ok, will add it.
> 
> @fengshunli i've also found out that `trivy-server` uses [serviceAccountName: trivy-operator](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/trivy-server.yaml#L58). But this service account is not created by helm. Is it ok if I will add it in the same PR?

@MaxFedotov the service accout is created in helm

**Comment by fengshunli** [comment]
Update the md, add a set parameter, and check it @MaxFedotov

**Comment by MaxFedotov** [comment]
@chen-keinan 

but the thing is that its name is 

https://github.com/aquasecurity/trivy-operator/blob/705873e294f8644c35e69b2d58a6dcc90ab7a13c/deploy/helm/templates/rbac.yaml#L6

which is generated as 
https://github.com/aquasecurity/trivy-operator/blob/44edfd66e780cf6518a05514b15beb81b6075465/deploy/helm/templates/_helpers.tpl#L56-L65

but in `statefulset` it is hardcoded as
https://github.com/aquasecurity/trivy-operator/blob/705873e294f8644c35e69b2d58a6dcc90ab7a13c/deploy/helm/templates/trivy-server.yaml#L58

what I wanted to do is to set it to 
https://github.com/aquasecurity/trivy-operator/blob/705873e294f8644c35e69b2d58a6dcc90ab7a13c/deploy/helm/templates/deployment.yaml#L27

the same way, as for operator deployment

**Comment by chen-keinan** [comment]
@MaxFedotov sound good, you can make it in same PR if you wish

**Comment by MaxFedotov** [comment]
@chen-keinan done

**Review by fengshunli — CHANGES_REQUESTED** [review]
test

**Comment by fengshunli** [comment]
> and one more thing I would like to add - support for `nodeSelector` for `trivy-server`

Will the affinity be better

**Comment by MaxFedotov** [comment]
That depends on the use-case :) we use nodeSelector to schedule pod on correct tenant nodes

**Comment by chen-keinan** [comment]
lgtm 🚀

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
