### PR TITLE
chore: platform and type - no metadata values

### LINKED ISSUE #2178: Ressource creation of k8s-cis-1.23 fails with Helm chart v0.24.0
I updated the operator Helm chart from 0.23.3 to 0.24.0 and now the clustercompliancereport `k8s-cis-1.23` sync/re-creation fails.

It seems the following two lines are responsible, which were added with a change in the 0.24.0 release:

https://github.com/aquasecurity/trivy-operator/blob/df12b1ee866c233f3a896b9e3558a22a1aa4a15c/deploy/helm/templates/specs/k8s-cis-1.23.yaml#L6-L7

image

### PR DESCRIPTION
**Pull request by Dimonyga**
remove
platform: k8s
type: cis
from metadata
fixes #2178

### CODE REVIEW

**Review by Dimonyga — COMMENTED** [review]
platform and type not a part of metadata

**Comment by chen-keinan** [comment]
@Dimonyga thanks for the catch up, please sigh the CLA

**Comment by Dimonyga** [comment]
> @Dimonyga thanks for the catch up, please sigh the CLA

Done

**Review by chen-keinan — APPROVED** [review]
@Dimonyga lgtm 🚀 thank you for the contribution

**Pull request merged**
