### PR TITLE
feat: Flag for changing default cache-dir parameter

### LINKED ISSUE #1603: Flag for changing default cache-dir parameter
This will be useful for using a custom image with existing vulnerability index databases. At the moment the `cache-dir` path is [hardcoded](https://github.com/aquasecurity/trivy-operator/blob/86aacdff2422c72da7c21603008c901f5066cf13/pkg/plugins/trivy/image.go#L536-L537) and the scan job has a next volumes configuration which overwrites anything in `tmp`, so you cannot store DBs there:

```yaml
spec:
  volumes:
    - name: tmp
      emptyDir: {}
    - name: scanresult
      emptyDir: {}
```

### PR DESCRIPTION
**Pull request by ahalay**
## Related issues
- Close #1603

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@ahalay  lgtm. one comment maybe you want to add it also support for `filesystem` mode

**Comment by ahalay** [comment]
> @ahalay lgtm. one comment maybe you want to add it also support for `filesystem` mode

added

**Comment by chen-keinan** [comment]
@ahalay please rebase with upstream, it will fix the `chart-tessting` issue

**Comment by ahalay** [comment]
> @ahalay please rebase with upstream, it will fix the `chart-tessting` issue

@chen-keinan done

**Comment by chen-keinan** [comment]
lgtm 🚀 thanks for the contribution

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
