### PR TITLE
feat: split trivy.imageRef into trivy.repository and trivy.tag

### LINKED ISSUE #522: Please break trivy.imageRef into separate pieces
To fetch scanner image from private mirror, now we have to override trivy.imageRef with full path with registry, repository and image tag. As a consequence, scanner image will be hardcoded and won't update during helm release updating, unlike trivy-operator's image, that have separate image tag option in values.yaml. Now we have to manually update trivy scanner image reference.

Could you separate trivy.imageRef to registry, repository and tag? Or maybe to image path and tag.

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

## Description

This PR is related to #522. We use in our company a private registry, and while we can seperate for the operator the registry from the tag it was not possible for the trivy image itself. 

With this PR we can do this, and don't have to think about to check the `tag` when we update the operator itself.

## Related issues
- Close #522 

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)

### CODE REVIEW

**Comment by chen-keinan** [comment]
@dirien Look good!! couple of comments: 

- Run : `make generate-all` to re-generate `deploy/static/trivy-operator.yaml`

- update [docs](https://github.com/aquasecurity/trivy-operator/blob/main/docs/vulnerability-scanning/trivy.md) with updated params 

once checks passes we are good for merge

**Comment by dirien** [comment]
Thanks for the feedback @chen-keinan. Done and ready to review when you are 😄

**Comment by chen-keinan** [comment]
> Thanks for the feedback @chen-keinan. Done, and ready to review when you are 😄

cool ,We need also to update the [initConfig](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/vulnerabilityreport/suite_test.go#L100) for the tests to pass

**Comment by dirien** [comment]
Sorry @chen-keinan for my n00b style! Now I run `make test` to ensure that all test are running  through without an error! 😅

**Comment by chen-keinan** [comment]
@dirien LGTM 🚀  thank you for the contribution , I'm holding merge as I want to make a patch release with security fixes
 #529 #531   , we can marge it afterwards.

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
