### PR TITLE
build(deps): bump golang.org/x/oauth2 from 0.1.0 to 0.5.0

### PR DESCRIPTION
**Pull request by fengshunli**
## Related issues
- Close #XXX

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by fengshunli** [comment]
> @fengshunli as discussed , no need to bump dependencies , there is a dependency bot for it. I suggest to close this PR

This new version, bots can't detect

**Comment by chen-keinan** [comment]
> > @fengshunli as discussed , no need to bump dependencies , there is a dependency bot for it. I suggest to close this PR
> 
> This new version, bots can't detect

currently lets keep the current version.

**Comment by fengshunli** [comment]
Rely on updating the latest version to avoid vulnerability risk

**Comment by chen-keinan** [comment]
> Rely on updating the latest version to avoid vulnerability risk

we have a nightly build who scan for vulnerabilities , and if one found we update the dependency

**Comment by fengshunli** [comment]
not scanned

**Comment by chen-keinan** [comment]
> not scanned

Security management doesn't mean bump version to solve potential vulnetability.
Lets keep the existing version , no need to bump it

**Comment by fengshunli** [comment]
You can change weekly to daily

**Pull request closed without merging**
