### PR TITLE
docs: restructuring docs like in Trivy

### PR DESCRIPTION
**Pull request by AnaisUrlichs**
## Description

I changed the docs similar to how we changed the Trivy docs.

One thing I am not happy with is the installation section, maybe we can move some of those docs somewhere else or maybe within getting-started I could add some files within a reference folder e.g. reference/troubleshooting.md

Thoughts?
Screenshot 2022-08-03 at 17 20 14

### CODE REVIEW

**Comment by chen-keinan** [comment]
> ## Description
> I changed the docs similar to how we changed the Trivy docs.
> 
> One thing I am not happy with is the installation section, maybe we can move some of those docs somewhere else or maybe within getting-started I could add some files within a reference folder e.g. reference/troubleshooting.md
> 

@AnaisUrlichs sure,  shift docs as you think it should be I'm open minded for having  new look and feel

**Comment by AnaisUrlichs** [comment]
Maybe @itaysk can take a look, too -- I did not change that much.
Also, would wait until we merge the changes to the Trivy docs and then merge the ones here, too

**Comment by chen-keinan** [comment]
@AnaisUrlichs LGTM 🚀  Please rebase the branch with upstream.

**Comment by chen-keinan** [comment]
lgtm 🚀

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
