### PR TITLE
rename the CRD files to match the controller-gen naming convention

### PR DESCRIPTION
**Pull request by padlar**
This patch is in preparation to switchover to the controller-gen for
generating CRD files from Go marker code. More importantly it makes it
easier to review the patch.

Related to #204

### CODE REVIEW

**Comment by erikgb** [comment]
I think the compliance CRDs should be moved back to the crd folder, since I do not think we are able to control the CRD generation to that level of detail. Or do you have another plan for this @padlar? This means (partly) reverting https://github.com/aquasecurity/trivy-operator/pull/109. CC @josedonizetti

**Comment by padlar** [comment]
> I think the compliance CRDs should be moved back to the crd folder (with the generate-names), since I do not think we are able to control the CRD generation to that level of detail. Or do you have another plan for this @padlar? This means (partly) reverting #109. CC @josedonizetti

this PR is about just renaming the CRD files. I was going to suggest moving the compliance CRDs back into the crd folder in the next PR as its not possible to generate the CRD files into 2 different folders automatically. Either manually move the compliance CRDs after generation or add a copy command post generation.

**Comment by chen-keinan** [comment]
@padlar The compliance CRDs cannot be moved to crd folder at this point. 
while suggesting auto generation for crds , need to see how to overcome custom validation on crds which we do not wish to lose. #232

**Comment by chen-keinan** [comment]
LGTM 🚀

**Review by chen-keinan — APPROVED** [review]

**Review by josedonizetti — APPROVED** [review]

**Pull request merged**
