### PR TITLE
Extraction of log reading logic to defer its close

### PR DESCRIPTION
**Pull request by 1003n40**
## Description
What we currently do is that we fetch the stream, but when error occurs while unmarshalling we can't close the log reader stream, which stays in memory while gc finds and deletes it. As an idea was to extract the logic to standalone function which does the fetching of log buffer and defers on closing it.

### CODE REVIEW

**Comment by chen-keinan** [comment]
@1003n40 thank you for the contribution , did you meant to change the `values.yaml` file

**Comment by 1003n40** [comment]
@chen-keinan This isn't related to any code with the `values.yaml`, it is related to possible OOM of the operator when handling multiple logs that are with cut off logs (aka. json outputs).

**Comment by chen-keinan** [comment]
> @chen-keinan This isn't related to any code with the `values.yaml`

OK , Can you please remove the changes from the values.yaml on this PR.

**Comment by 1003n40** [comment]
> > @chen-keinan This isn't related to any code with the `values.yaml`
> 
> OK , Can you please remove the changes from the values.yaml on this PR.

Ohh my error :).

**Comment by chen-keinan** [comment]
LGTM 🚀

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
