### PR TITLE
chore: bump trivy 0.38.0

### LINKED ISSUE #1010: Update trivy to v0.38.0

### PR DESCRIPTION
**Pull request by chen-keinan**
## Description
bump trivy 0.38.0

## Related issues
- Close #1010

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by angularprojects4all** [comment]
I think we are loosing basic scan here, according to 0.38.0 / 0.38.1
faced issue with python based dockers.

the issue remained same irrespective of the option _--offline-scan_ (and / or) _--scanners vuln_

2023-03-03T08:44:43.816Z        INFO    Vulnerability scanning is enabled
2023-03-03T08:44:43.816Z        INFO    Secret scanning is enabled
2023-03-03T08:44:43.816Z        INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-03T08:44:43.816Z        INFO    Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection

```
2023-03-03T08:44:49.420Z        INFO    JAR files found
2023-03-03T08:44:49.422Z        INFO    Analyzing JAR files takes a while...
2023-03-03T08:44:49.601Z        FATAL   image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:125335cc58b0044b35fab83684d58e6ce76dd9f466af964e859fbe7bad8e5eea): post analysis error: post analysis error: walk dir error: on file: jar/war/ear/par parse error: zip error: zip: not a valid zip file
```

Does anyone else in the world facing same kinda issue?

**Comment by chen-keinan** [comment]
@angularprojects4all are you testing with `tirvy-operator v0.12.0-rc` ?

**Comment by angularprojects4all** [comment]
@chen-keinan,
I'm not using `tirvy-operator v0.12.0-rc` ,  installed trivy (the core? or I can call it (aquasecurity/trivy)), does trivy-operator usage would have been resolved in scanning?

or do you want me to direct me to correct thread!!

**Comment by chen-keinan** [comment]
> @chen-keinan, I'm not using `tirvy-operator v0.12.0-rc` , installed trivy(yum install trivy) which is 0.38.0 version ), this is working till the version 0.37.3 but after updating the version we can able to see the issue
can you pass you input in `trivy` slack channel or raise an issue with trivy repo , probably with catch attention faster

**Comment by angularprojects4all** [comment]
FYI: created issue in trivy repo
for more visibility & reach placing link here.
https://github.com/aquasecurity/trivy/issues/3760

**Comment by lucassaldanha** [comment]
> Does anyone else in the world facing same kinda issue?

Yes. We started to see the same issue in our CI setup.

Example: https://app.circleci.com/pipelines/github/ConsenSys/teku/24065/workflows/2e729ece-47fa-4a51-98da-81b64a72f5fc/jobs/174786

**Comment by angularprojects4all** [comment]
Looks like things were sorted out in 0.38.2+
thanks

**Comment by angularprojects4all** [comment]
> I think we are loosing basic scan here, according to 0.38.0 / 0.38.1 faced issue with python based dockers.
> 
> the issue remained same irrespective of the option _--offline-scan_ (and / or) _--scanners vuln_
> 
> 2023-03-03T08:44:43.816Z INFO Vulnerability scanning is enabled 2023-03-03T08:44:43.816Z INFO Secret scanning is enabled 2023-03-03T08:44:43.816Z INFO If your scanning is slow, please try '--scanners vuln' to disable secret scanning 2023-03-03T08:44:43.816Z INFO Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection
> 
> ```
> 2023-03-03T08:44:49.420Z        INFO    JAR files found
> 2023-03-03T08:44:49.422Z        INFO    Analyzing JAR files takes a while...
> 2023-03-03T08:44:49.601Z        FATAL   image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:125335cc58b0044b35fab83684d58e6ce76dd9f466af964e859fbe7bad8e5eea): post analysis error: post analysis error: walk dir error: on file: jar/war/ear/par parse error: zip error: zip: not a valid zip file
> ```
> 
> Does anyone else in the world facing same kinda issue?


Looks like things were sorted out in 0.38.2+
thanks

**Pull request merged**
