### PR TITLE
fix: helm param gcr service account auth

### LINKED ISSUE #2073: Google Container Registry / Google Artifact Registry ImagePullSecret connection problem
**What steps did you take and what happened:**

1. I had an old version of trivy-operator running with the helm chart_version: 0.18.0. which was working using the [GCR/GAR](https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key) in order to pull the images that have to be scanned.

1. In order to setup the authentication, I just followed your documentation and I used the [second option](https://aquasecurity.github.io/trivy-operator/latest/tutorials/private-registries/#second-option-using-an-imagepullsecret-to-access-containers-from-the-private-registry  )

1. I've updated  the helm version and bump it to the last stable version 0.22.1 (I knew this bump was a little bit risky)

1. As soon as I bumped the version, all the scan-vulnerabilityreport started to end up in `error` state. So I checked the logs and I saw the following:
```
Defaulted container "XXXXXXX" out of: XXXXXXX, YYYY-YYY-YY-YYYY-YYYYYYY (init)
^[[A2024-05-15T10:52:25.529Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: 4 errors occurred:
	* docker error: unable to inspect the image (europe-west1-docker.pkg.dev/ZZZZZZZ/ZZZZZZ/ZZZZZZZZ:master): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* containerd error: containerd socket not found: /run/containerd/containerd.sock
	* podman error: unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* remote error: GET https://europe-west1-docker.pkg.dev/v2/token?scope=repository%ZZZZZZZ%ZZZZZZ%2FZZZZZZZZ%3Apull&service=: DENIED: Unauthenticated request. Unauthenticated requests do not have permission "artifactregistry.repositories.downloadArtifacts" on resource "projects/ZZZZZZZ/locations/europe-west1/repositories/ZZZZZZZ" (or it may not exist)
```
**What did you expect to happen:**
I expected to trivy-operator keep working like it was working before.

**Anything else you would like to add:**

I started to check all the possible Google container registry PR related to that problem:

- https://github.com/aquasecurity/trivy-operator/issues/392
- https://github.com/aquasecurity/trivy-operator/issues/1095 (similar but not the same case)
- https://github.com/aquasecurity/trivy-operator/issues/1298
- https://github.com/aquasecurity/trivy-operator/pull/1404

And after investigate for a while I realized that maybe can be related to this one:
- https://github.com/aquasecurity/trivy-operator/pull/1404

Why? Because on this MR,  you are checking if the `key` is` _json_key` but following the [Google Artifact Registry configuration document](https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key)  you can have either a `_json_key` or a `_json_key_base64`.
In case that you have a `_json_key_base64` all the content of your file is base64-encoded so I have the suspect that trivy mounts the credentials correctly from the secret stored at `scan-vulnerabilityreport-xxxx` but its encoded base64 so trivy is not able to use it. 
I have been doing some "tests" and this issue begins to happen at the TAG v0.16.1.
I 've checked the [diff between the 2 tags version](https://github.com/aquasecurity/trivy-operator/compare/v0.16.0...v0.16.1) and I realized that was when you introduced the changes of the:
- https://github.com/aquasecurity/trivy-operator/pull/1404

Is it possible that the problem relays on the fact that on the file [`pkg/plugins/trivy/plugin.go` ](https://github.com/aquasecurity/trivy-operator/compare/v0.16.0...v0.16.1#diff-9b7dda0e24a5484db32812ffed2b2a9be64b2b5169a033df287219de304df6b1R1063) we are checking just `_json_key` and should be as well `_json_key_base64` and implement a function that decode it?
Im quite confused because on v0.16.0 is working.

We can not change our `kubernetes.io/dockerconfigjson` to use `_json_key` and not `_json_key_base64` because we want to avoid to have problems with the accolade and other special characters.

Can you check it please? Im stuck on the tag v0.16.0 but using the helm values from the v0.20.1 and it works but I would like to able to bump it for consistency

### PR DESCRIPTION
**Pull request by chen-keinan**
## Description
helm param gcr service account auth

## Related issues
- Close #2073

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@tidusete do you know how to build the project from this PR and test it to make sure it works for you ?

**Comment by tidusete** [comment]
@chen-keinan I have been trying to make it work but without luck.
Im defining on the configmap:
```
  name: trivy-operator
  namespace: default
  data:
    scanJob.useGCRServiceAccount: testing
 ````
 But I believe this condition trivyoperator.GetDefaultConfig().GetScanJobUseGCRServiceAccount() is always giving me true although I have defined on the trivy-operator configmap the following Key.
 As soon as I forced this condition to false it worked:
 ```
 if CheckGcpCrOrPrivateRegistry(c.Image) &&
                               trivyoperator.GetDefaultConfig().GetScanJobUseGCRServiceAccount() && false {
```
So basically the problem relays on the function `trivyoperator.GetDefaultConfig().GetScanJobUseGCRServiceAccount()`

From which helm version should I work on that point? Should I forward everything to the last helm version and put on top of that the container image that I'm building with your changes?

**Comment by chen-keinan** [comment]
@tidusete if you want to run from helm do the following.
steps:
-  building trivy-operator binary
```sh
cd ~/<your workspace>/trivy-operator/cmd/trivy-operator
GOOS=linux GOARCH=arm64/amd64 go build -o trivy-operator
```
- building operator image: <docker hub user>/trivy-operator:<tag>
```sh
mv trivy-operator ~/<your workspace>/trivy-operator/build/trivy-operator/trivy-operator

cd ~/<your workspace>/trivy-operator/build/trivy-operator

docker build -t <docker hub user>/trivy-operator:<tag> .
```
- publishing operator image: <docker hub user>/trivy-operator:<tag>
```sh
docker push <docker hub user>/trivy-operator:<tag>"
```

update the [deployment image ](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/deployment.yaml#L38)  with the one you just build and published

**Comment by chen-keinan** [comment]
@tidusete any update ?

**Comment by tidusete** [comment]
I will try to do it today

**Comment by tidusete** [comment]
Hey @chen-keinan I have been following all what you said but I have no luck.

1. building trivy-operator binary
2. building operator image: /trivy-operator
3. publishing operator image: /trivy-operator
4. Modifying the configmap:
```
kind: ConfigMap
name: trivy-operator
data:
  scanJob.useGCRServiceAccount: 'false'
```
5. Modifying the deployment of the operator and adding there my custom image...

I have the feeling that this var  `scanJob.useGCRServiceAccount: 'False'` is not being set on the trivy operator. Is it possible? As I said before, the only way to make it work was forcing to be always false the condition:
https://github.com/aquasecurity/trivy-operator/pull/2108/files#diff-53a92550719283e3e24a05f5be379432b7015f20730b85c8803b9c0855556909R213
```
if CheckGcpCrOrPrivateRegistry(c.Image) &&
                              trivyoperator.GetDefaultConfig().GetScanJobUseGCRServiceAccount() && false {
```

**Comment by chen-keinan** [comment]
@tidusete are you using helm install after doing al of the steps above ?

**Comment by chen-keinan** [comment]
@tidusete let me know if now it works for you and I'll merge it

**Comment by tidusete** [comment]
Will try to do it today as well

**Comment by tidusete** [comment]
Works like a charm!

**Comment by chen-keinan** [comment]
> Works like a charm!

Thanks for the update, I'll merge it now.

**Comment by 34fathombelow** [comment]
I see a new helm chart was published, but I believe this would require a newer `appVersion` to use this fix. Correct?

**Comment by chen-keinan** [comment]
@34fathombelow the fix on the PR has not yet been released, only merged , will be out with `trivy-operator v0.22.0` hopefully later on this week

**Pull request merged**
