### PR TITLE
feat: added configurable appProtocol to metrics service

### LINKED ISSUE #1866: configurable appProtocol in metrics service
I want to scrape metrics from trivy via istio service mesh. Unfortunately it seems like trivy is not supporting HTTP2 which is the default in prometheus (and I don't want to change that).

Now I want to change the appProtocol of the trivy-operator metrics service to `http`. At the moment this is not configurable.

I would implement this feature myself ❤️

### PR DESCRIPTION
**Pull request by seekermarcel**
## Description

I'm not sure about the default value `TCP`. I think thats the Kubernetes default but not sure if trivy has something specific.

## Related issues
- Close #1866

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [X] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [X] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@seekermarcel try running `mage generate:docs`

**Comment by seekermarcel** [comment]
I already have. No changes when I run it again

**Comment by chen-keinan** [comment]
@seekermarcel I see now , you need to run `mage generate:all` to update the static yamls

**Comment by seekermarcel** [comment]
@chen-keinan done. Looks like it needed some updates 😅

**Comment by chen-keinan** [comment]
@seekermarcel I think you addition to static file include more then it should , only the following should be added :
```yaml
      port: 80
       targetPort: metrics
       protocol: TCP
+      appProtocol: TCP
   selector:
     app.kubernetes.io/name: trivy-operator
     app.kubernetes.io/instance: trivy-operator
```

**Review by chen-keinan — APPROVED** [review]
@seekermarcel lgtm 🚀 thanks for the contribution

**Pull request merged**
