### PR TITLE
Add vulnerability class to the report

### PR DESCRIPTION
**Pull request by fardin01**
## Description
This commit adds the vulnerability class (`os-pkgs` or `lang-pkgs`) to the report so that it becomes possible to identify vulnerabilities based on this.

## Related issues
Fixes https://github.com/aquasecurity/trivy-operator/issues/564

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@fardin01 if you wish to discuss it in details I'll be happy. you can find me on Slack

**Comment by fardin01** [comment]
@chen-keinan Thanks for your feedback, it's certainly better this way. Please take another look. Once you're okay with the changes I will update the docs too.

**Comment by chen-keinan** [comment]
@fardin01 look good , couple of comments:
- need to update comment on [supported values](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L178) on Helm values yaml file 
- need to update [docs](https://github.com/aquasecurity/trivy-operator/blob/c5447c566c07b4b95fca5573fdaf33c7f4fc8f4c/docs/vulnerability-scanning/trivy.md) as well

**Comment by chen-keinan** [comment]
@fardin01 LGTM 🚀  thanks you for the contribution , I'm cutting a release today , I'll merge the code after the release.

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
