### PR TITLE
feat: add option to use trivy in offline-scan mode

### LINKED ISSUE #657: Scans take 10+ min in air-gapped cluster for some images as trivy tries to reach search.maven.org
**What steps did you take and what happened:**

I've deployed the trivy-operator successfully on a cluster running on [RKE2](https://docs.rke2.io/) using the Helm chart. Operator is starting as expected and logs do show that it is also being triggered when workloads are created. Unfortunetaly, it is not able to scan images and returns the following error:

```json
{
    "level": "error",
    "ts": 1667817961.652814,
    "logger": "reconciler.vulnerabilityreport",
    "msg": "Scan job container",
    "job": "trivy-operator/scan-vulnerabilityreport-788955dd59",
    "container": "nginx",
    "status.reason": "Error",
    "status.message": "2022-11-07T10:45:59.392Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (nginx:1.16): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* Get \"https://index.docker.io/v2/\": dial tcp 18.206.20.10:443: connect: connection refused\n\n\n",
    "stacktrace": "github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:551\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport.(*WorkloadController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller.go:376\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"
}
```

It looks like it can't find the `containerd.sock` as it's only looking in one default place, i.e. `/run/containerd/containerd.sock`.

RKE2 does use containerd as its CRI, but it does not rely on the system provided containerd setup and instead provids its own builtin containerd, thus also using its own path for the socket, i.e. `/run/k3s/containerd/containerd.sock`. This is not picked up by trivy / the trivy-operator and thus the above errors.

**What did you expect to happen:**

Deployed the trivy-operator and deployed an example workload. Expected to get a report on vulnerabilities.

**Anything else you would like to add:**

It looks like there is an experimental way in trivy to change the path used for the socket, see <https://aquasecurity.github.io/trivy/v0.34/docs/advanced/container/containerd/>.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
  - `{"level":"info","ts":1667817292.0559022,"logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.5.0","Commit":"e43a4c63a33aa35c0d1c2c3600be41b6d0ded7d0","Date":"2022-10-30T12:26:08Z","Executable":""}}`
- Kubernetes version (use `kubectl version`):
  - `version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+rke2r1", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-13T17:54:54Z", GoVersion:"go1.19.2 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}` 
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
  - rke2 running on RHEL 8.6

### PR DESCRIPTION
**Pull request by nobbs**
## Description

This implements an option `trivy.offlineScan` in `trivy-operator-trivy-config` configmap which will set the `TRIVY_OFFLINE_SCAN` env var for the scan pods enabling the offline scan mode of trivy, thus preventing it from trying to access <https://search.maven.org> to get more information on vulnerabilities in container images with java related files.

Info on the offline scan mode for air-gapped setups of trivy can be found in <https://aquasecurity.github.io/trivy/v0.34/docs/advanced/air-gap/#run-trivy-with-skip-update-and-offline-scan-option>

## Related issues
- Close #657 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@nobbs thank you for the contribution , few comments :
`trivy-operator` has three modes for scanning jobs :
- `fs scanning`
       - can support offline mode
       - require to disable `init container` as its going to fail if no access to internet
- `standalone scanning` 
       -  can support offline mode
       -  require to disable `init container` as its going to fail if no access to internet
- `client/server scanning`
       - do not support offline mode

it is require to add comment /ref on how to copy `trivy db` to cluster `cache` folder

Let me know if you have any question

**Comment by nobbs** [comment]
Hey @chen-keinan, thanks for the comment. I guess I wasn't entirely clear, how this works. All this new options does, is setting the `TRIVY_OFFLINE_SCAN` env var, which is equivalent to passing `--offline-scan` to `trivy`. 

This option does not block general internet usage by Trivy, it only disables the lookup of additional information by `trivy`, or more precisely, the `go-dep-parser` that is used there.

I've checked the use of this offline scan flag in both of the aforementioned repositories, it has no effect on the download of the trivy database files, only on the access to additional information on maven.org. 

So, in a real air-gapped setup this will not help, as you still have to get the database from somewhere. There, the behaviour is as you described for the 3 modes. But that is not what I want to implement. With this option enabled, it will only prevent the requests to the maven.org endpoints. 

(We've got an internal docker registry mirror, so pulling the database does work for us, but not the access to the maven URLs.)

Should I update the docs / values file and point to the trivy docs for clarification what this option does?

**Comment by chen-keinan** [comment]
@nobbs I understand , so all you want to implement is this :
 `if you want to scan Java dependencies such as JAR and pom.xml, you need to specify --offline-scan since Trivy tries to issue API requests for scanning Java applications by default.`

**Comment by nobbs** [comment]
yeah, exactly :D

**Review by chen-keinan — APPROVED** [review]

**Comment by Jeet-14** [comment]
@nobbs `--skip-update` is flag for disabling the vuln DB in normal trivy setup. (Ref: https://aquasecurity.github.io/trivy/v0.34/docs/advanced/air-gap/#run-trivy-with-skip-update-and-offline-scan-option)  

I am playing around with trivy operator helm chart, in values.yaml there is `command: image` under trivy section` on which if we modify `command: image --skip-update` is should prevent DB pull from internet. but the question is then how to supply DB?

**Comment by chen-keinan** [comment]
> @nobbs `--skip-update` is flag for disabling the vuln DB in normal trivy setup. (Ref: https://aquasecurity.github.io/trivy/v0.34/docs/advanced/air-gap/#run-trivy-with-skip-update-and-offline-scan-option)
> 
> I am playing around with trivy operator helm chart, in values.yaml there is `command: image` under trivy section on which if we modify `command: image --skip-update` is should prevent DB pull from internet. but the question is then how to supply DB?

@Jeet-14 if you use `image` command , the db will be downloaded via [init container](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L494)

**Pull request merged**
