### PR TITLE
feat: add local cache mode for scanner

### LINKED ISSUE #1342: Allow InitContainer to pull vulnerability-db from private registry
### Discussed in https://github.com/aquasecurity/trivy-operator/discussions/1341

<div type='discussions-op-text'>

<sup>Originally posted by **yanehi** July  6, 2023</sup>
I would like to run the trivy-operator in standalone mode in an air-gapped environment. For this we use our own trivy-image, which contains the vulnerability databases.

For all scan-jobs the project works as expected. However, the InitContainer started by the trivy-operator always bypasses the cache (since I can't give it a pvc) and unfortunately can't download our vulnerability-db from our private registry. An ImagePullSecret is set at the podlevel and already allows the InitContainer itself to pull the image from our private registry. However, in the trivy command it tries to load the db from our private registry:

Command
```
  InitContainer: 
   Command:
      trivy
    Args:
      --cache-dir
      /tmp/trivy/.cache
      image
      --download-db-only
      --db-repository
      <private-registry-name>
```

```
2023-07-06T10:23:04.261Z  ^[[34mINFO^[[0m           DB Repository: <private-registry-name>
2023-07-06T10:23:04.261Z  ^[[34mINFO^[[0m           Downloading DB...
2023-07-06T10:23:04.519Z  ^[[31mFATAL^[[0m          init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
                          * GET https://<registry-url>/jwt/auth?scope=repository%3A<repository-name>%2Foci%2F<image-name>%3Apull&service=container_registry: DENIED: access forbidden
```

Is there any way at this point to pass in credentials so that it can pull the db (image) from our private registry?</div>

### PR DESCRIPTION
**Pull request by zhcli**
## Description
Adding local cache mode for vulnerability scanner

## Related issues
- Close #1342 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by zhcli** [comment]
Hi @chen-keinan , drafted this PR to address #1341. Let me know what you think about this approach.

**Comment by chen-keinan** [comment]
@zhcli the only different between `standalone` to `local cache`

id that it has different command on initContainer ? 

example :

standalone : 
```go 
Command: []string{
			"trivy",
		},
		Args: []string{
			"--cache-dir",
			"/tmp/trivy/.cache",
			"image",
			"--download-db-only",
			"--db-repository",
			dbRepository,
		},
```
`loca-cache` 
```go
Command: []string{
			"/bin/sh",
		},
		Args: []string{
			"-c", fmt.Sprintf("mkdir /tmp/trivy-db && cp -rv %s /tmp/trivy-db && chmod -R 777 /tmp/trivy-db", cacheDir),
		},
```

**Comment by zhcli** [comment]
Hi @chen-keinan , yes it is.
I tried to remove the init container but was unsuccessful, the trivy run time container file system is read-only, so I have to adopt a read-write volume. I was able to reduce an init container for file system scan though.
To avoid code duplication, I can merge the logic into original standalone functions by introducing a new parameter to handle local cache mode.
Let me know.

**Comment by chen-keinan** [comment]
> Hi @chen-keinan , yes it is. I tried to remove the init container but was unsuccessful, the trivy run time container file system is read-only, so I have to adopt a read-write volume. I was able to reduce an init container for file system scan though. To avoid code duplication, I can merge the logic into original standalone functions by introducing a new parameter to handle local cache mode. Let me know.

@zhcli  is setting this [helm flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L216C3-L216C21) will not do the work for not running initContainer

**Comment by zhcli** [comment]
> > Hi @chen-keinan , yes it is. I tried to remove the init container but was unsuccessful, the trivy run time container file system is read-only, so I have to adopt a read-write volume. I was able to reduce an init container for file system scan though. To avoid code duplication, I can merge the logic into original standalone functions by introducing a new parameter to handle local cache mode. Let me know.
> 
> @zhcli is setting this [helm flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L216C3-L216C21) will not do the work for not running initContainer

@chen-keinan I am reading the codes correctly, the `skipInitContainers` does not have any actual effect on the init containers. I also believe if the init container is taken away from the Standalone image/FS scan mode, they will fail.

**Comment by chen-keinan** [comment]
> > > Hi @chen-keinan , yes it is. I tried to remove the init container but was unsuccessful, the trivy run time container file system is read-only, so I have to adopt a read-write volume. I was able to reduce an init container for file system scan though. To avoid code duplication, I can merge the logic into original standalone functions by introducing a new parameter to handle local cache mode. Let me know.
> > 
> > 
> > @zhcli is setting this [helm flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L216C3-L216C21) will not do the work for not running initContainer
> 
> @chen-keinan I am reading the codes correctly, the `skipInitContainers` does not have any actual effect on the init containers. I also believe if the init container is taken away from the Standalone image/FS scan mode, they will fail.

@zhcli true,  it will fail because it do not have `vulnedb` on  `TRIVY_CACHE_DIR` but if the backed trivy image (for air gapped env) will include the vulndb on `TRIVY_CACHE_DIR`, isn't it will solve the issue ? or I'm not understanding the req.

**Comment by zhcli** [comment]
@chen-keinan I was intended to remove all the init containers for local cache mode, however after that trivy complains about file systems permissions issue about its Vul DB files. It seems that I ran into the same issue as https://github.com/aquasecurity/trivy/discussions/4286

**Comment by chen-keinan** [comment]
> @chen-keinan I was intended to remove all the init containers for local cache mode, however after that trivy complains about file systems permissions issue about its Vul DB files. It seems that I ran into the same issue as [aquasecurity/trivy#4286](https://github.com/aquasecurity/trivy/discussions/4286)

qq: does the trivy image include vuln db in it ?

**Comment by zhcli** [comment]
> > @chen-keinan I was intended to remove all the init containers for local cache mode, however after that trivy complains about file systems permissions issue about its Vul DB files. It seems that I ran into the same issue as [aquasecurity/trivy#4286](https://github.com/aquasecurity/trivy/discussions/4286)
> 
> qq: does the trivy image include vuln db in it ?

Yes. My testing environment is docker desktop + kind. I built a trivy image with latest Vul DB, no matter which volume I put the DB files, trivy complains about permissions issue. I have to leverage an external volume with read-write permission.

**Comment by chen-keinan** [comment]
> > > @chen-keinan I was intended to remove all the init containers for local cache mode, however after that trivy complains about file systems permissions issue about its Vul DB files. It seems that I ran into the same issue as [aquasecurity/trivy#4286](https://github.com/aquasecurity/trivy/discussions/4286)
> > 
> > 
> > qq: does the trivy image include vuln db in it ?
> 
> Yes. My testing environment is docker desktop + kind. I built a trivy image with latest Vul DB, no matter which volume I put the DB files, trivy complains about permissions issue. I have to leverage an external volume with read-write permission.

can put it here an example how you build the vulndb with trivy image ?

**Comment by zhcli** [comment]
> > > > @chen-keinan I was intended to remove all the init containers for local cache mode, however after that trivy complains about file systems permissions issue about its Vul DB files. It seems that I ran into the same issue as [aquasecurity/trivy#4286](https://github.com/aquasecurity/trivy/discussions/4286)
> > > 
> > > 
> > > qq: does the trivy image include vuln db in it ?
> > 
> > 
> > Yes. My testing environment is docker desktop + kind. I built a trivy image with latest Vul DB, no matter which volume I put the DB files, trivy complains about permissions issue. I have to leverage an external volume with read-write permission.
> 
> can put it here an example how you build the vulndb with trivy image ?

@chen-keinan please see below
```
FROM ghcr.io/aquasecurity/trivy:0.46.0

RUN adduser -u 10000 -D -g '' trivyoperator trivyoperator

USER 10000

RUN trivy --cache-dir /home/trivyoperator/.cache image --download-db-only --db-repository ghcr.io/aquasecurity/trivy-db

RUN chmod -R 777 /home/trivyoperator/.cache

ENTRYPOINT ["trivy"]
```

**Comment by chen-keinan** [comment]
> > > > > @chen-keinan I was intended to remove all the init containers for local cache mode, however after that trivy complains about file systems permissions issue about its Vul DB files. It seems that I ran into the same issue as [aquasecurity/trivy#4286](https://github.com/aquasecurity/trivy/discussions/4286)
> > > > 
> > > > 
> > > > qq: does the trivy image include vuln db in it ?
> > > 
> > > 
> > > Yes. My testing environment is docker desktop + kind. I built a trivy image with latest Vul DB, no matter which volume I put the DB files, trivy complains about permissions issue. I have to leverage an external volume with read-write permission.
> > 
> > 
> > can put it here an example how you build the vulndb with trivy image ?
> 
> @chen-keinan please see below
> 
> ```dockerfile
> FROM ghcr.io/aquasecurity/trivy:0.46.0
> 
> RUN adduser -u 10000 -D -g '' trivyoperator trivyoperator
> 
> USER 10000
> 
> RUN trivy --cache-dir /home/trivyoperator/.cache image --download-db-only --db-repository ghcr.io/aquasecurity/trivy-db
> 
> RUN chmod -R 777 /home/trivyoperator/.cache
> 
> ENTRYPOINT ["trivy"]
> ```

thanks will check it up and update you

**Comment by chen-keinan** [comment]
@zhcli thanks for sharing the docker file , I was able to reproduce this issue.
the right approach will be 1st is to separate `cache flags` for `db` and `image` as suggested by this [discussion](https://github.com/aquasecurity/trivy/discussions/4286)
and then add a simple change in trivy-operator

the fix in `trivy` is simple you can raise a PR and I can help with it or I'll do it my self if you do not have time.
let me know wdyt

**Comment by zhcli** [comment]
> @zhcli thanks for sharing the docker file , I was able to reproduce this issue. the right approach will be 1st is to separate cache flags for `db` and `image` as suggested by this [discussion](https://github.com/aquasecurity/trivy/discussions/4286) and then add a simple change in `trivy-operator`
> 
> the fix in `trivy` is simple you can raise a PR and I can help with it or I'll do it my self if you do not have time. let me know wdyt

@chen-keinan thanks for testing, I can take a look the trivy issue when I have some spare times, most likely late weekend nights. Also are you in the trivy slack channel? I will join and communicate with you over there.

**Comment by gerbil** [comment]
Any progress here?

**Comment by tibuntu** [comment]
@chen-keinan any chance that this functionality is provided soon?

Can we help with a contribution or do you want to cover that internally?

**Comment by chen-keinan** [comment]
@tibuntu it has dependency on trivy to [support](https://github.com/aquasecurity/trivy/issues/5595) separate  cache folders for vulndb and layers , its look like issue is not yet supported, once it will be done then it will be easy fix

**Pull request closed without merging**
