### PR TITLE
feat: vulnerability scanner reports persistance enabled

### PR DESCRIPTION
**Pull request by cthtrifork**
## Description
If the purpose of the operator is simply to collect metrics for alerting, the vulnerability reports can be chosen not to be persisted. This is relevant as the operator right now submits reports that are too large for the etcd request limits.

## Related issues
- Helps https://github.com/aquasecurity/trivy-operator/issues/757

## Checklist
- [ ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by cthtrifork** [comment]
@chen-keinan Does this solution make sense and can you allow this workaround?
I looked at https://github.com/aquasecurity/trivy-operator/issues/442 but did not find a easy way to accomplish it.

**Comment by chen-keinan** [comment]
@cthtrifork the persistence to Etcd must happen, all reports reconciliation process depend on it, also metrics entry point and other. I do not see other way to work it.

**Comment by cthtrifork** [comment]
@chen-keinan Okay. I will close this again.

**Comment by chen-keinan** [comment]
@cthtrifork as I mention in issue the only solution (not best)  is encrypting the report data and make it available for metrics.
the downside , that you will not bae able to see report with kubectl , but it will be available via metrics

**Pull request closed without merging**
