### PR TITLE
build(deps): Bump golang.org/x/net from 0.6.0 to 0.7.0

### PR DESCRIPTION
**Pull request by fengshunli**
## Related issues
- Close #XXX

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@fengshunli we have dependency bot , no need to open PRs to bump dependencies

**Comment by fengshunli** [comment]
This golang.org/x/net dependent package has cve vulnerability, which can be prioritized

**Comment by chen-keinan** [comment]
> This golang.org/x/net dependent package has cve vulnerability, which can be prioritized

Trivy-operator has a [nightly job](https://github.com/aquasecurity/trivy-operator/actions/runs/4205854855/jobs/7298540238) /  `on demand` which check for `Critical` or `High` vulnerabilities, if found we fix it ASAP.

For `lower vulnerabilities severities` (Low / Med)  its ok to wait for dependency bot to pick it up.

**Comment by fengshunli** [comment]
ok

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
