### PR TITLE
fix: remove node selector

### LINKED ISSUE #1610: Node-collector stays in Pending state
We had an upgrade for trivy-operator from v16.0 to v16.4 (chart version 18.4) using ArgoCD. After the upgrade `trivy-operator` spins up `node-collector`. A few went fine, however we have one job which is scheduled on a cordoned node. Due to that, node-collector stays in pending mode, until we terminated it ourselves. I shared here the [logs](https://github.com/aquasecurity/trivy-operator/files/13249804/logs-insights-results.json) for reference. Dummy question is whether you have excluded cordoned nodes for scheduling, or it is race-condition that leads to this situation?

### LINKED ISSUE #1635: nodeCollector nodeSelector restricted
https://github.com/aws/karpenter/issues/4671

```
label kubernetes.io/hostname is restricted; specify a well known label: [karpenter.k8s.aws/instance-accelerator-count karpenter.k8s.aws/instance-accelerator-manufacturer karpenter.k8s.aws/instance-accelerator-name karpenter.k8s.aws/instance-category karpenter.k8s.aws/instance-cpu karpenter.k8s.aws/instance-encryption-in-transit-supported karpenter.k8s.aws/instance-family karpenter.k8s.aws/instance-generation karpenter.k8s.aws/instance-gpu-count karpenter.k8s.aws/instance-gpu-manufacturer karpenter.k8s.aws/instance-gpu-memory karpenter.k8s.aws/instance-gpu-name karpenter.k8s.aws/instance-hypervisor karpenter.k8s.aws/instance-local-nvme karpenter.k8s.aws/instance-memory karpenter.k8s.aws/instance-network-bandwidth karpenter.k8s.aws/instance-size karpenter.sh/capacity-type karpenter.sh/nodepool kubernetes.io/arch kubernetes.io/os node.kubernetes.io/instance-type node.kubernetes.io/windows-build topology.kubernetes.io/region topology.kubernetes.io/zone], or a custom label that does not use a restricted domain: [k8s.io karpenter.k8s.aws karpenter.sh kubernetes.io]"
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.18.4
- Kubernetes version (use `kubectl version`): 1.28 (EKS)
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Amazon Linux (EKS)

What can I do with the helm release to fix this?

### PR DESCRIPTION
**Pull request by chen-keinan**
## Description
fix: remove node selector

## Related issues
- Close #1635 
- Close #1610 1610

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).

### CODE REVIEW

**Comment by truongnht** [comment]
Thank, @chen-keinan . Let me check

**Comment by chen-keinan** [comment]
@truongnht ***Note:*** its not yet released , it will be out with `v0.17.0` unless you want to build it manually from source code

**Comment by truongnht** [comment]
hey @chen-keinan , when do you guys plan to cut `v0.17.0` release?

**Comment by chen-keinan** [comment]
> hey @chen-keinan , when do you guys plan to cut `v0.17.0` release?

by end of next week

**Comment by sathieu** [comment]
xref: https://github.com/aquasecurity/trivy-kubernetes/commit/c7e2f804481a7abfc6a5bcedcd7be0e94942a65c

**Comment by ledroide** [comment]
Issue is not fixed in v0.18.0. Node collector still has node selectors that tries to schedule on the control plane that taints forbid this.
```
NAME                                  COMPLETIONS   DURATION   AGE   APP
job.batch/node-collector-65f99f5bd6   0/1           99s        99s

NAME                                  READY   STATUS    RESTARTS   AGE     APP
pod/node-collector-65f99f5bd6-x7ksn   0/1     Pending   0          2m15s   node-collector
```
```
Node-Selectors:              kubernetes.io/hostname=k8ststmaster-1
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m48s  default-scheduler  0/6 nodes are available: 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/6 nodes are available: 6 Preemption is not helpful for scheduling..
```
Workaround : disable infraAssessment scanner for trivy-operator.
```
OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED="false"
```

**Comment by chary1112004** [comment]
I face same issue with pod node-collector is pending and version is v0.18.1

**Comment by chary1112004** [comment]
@chen-keinan yes, we have some nodes using taints/tolerations, some nodes not using taints/tolerations

**Comment by chen-keinan** [comment]
> @chen-keinan nodes are working (not in shutting status) and I deploy latest version of trivy. Yes, we have some nodes are using taints/tolerations, some nodes are not using taints/tolerations

are you using [toleration](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L201) setting in operator

**Comment by chary1112004** [comment]
@chen-keinan thanks, I have just added toleration as suggestion however it does not work. Even without toleration it should locate to nodes without taints.

**Comment by chen-keinan** [comment]
> @chen-keinan thanks, I have just added toleration as suggestion however it does not work. Even without toleration it should locate to nodes without taints.

I see , then my suggestion to you is to remove toleration and use the [excludeNodes](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L591) param to ignore nodes by labels , so you could ignore these specific node which keep pod in pending state.

**Comment by chary1112004** [comment]
@chen-keinan I see this property exclude nodes from scanning by label however I expect these nodes are still scanning.

```
# -- excludeNodes comma-separated node labels that the node-collector job should exclude from scanning (example kubernetes.io/arch=arm64,team=dev)
  excludeNodes:
```

**Comment by chen-keinan** [comment]
> @chen-keinan I see this property exclude nodes from scanning by label however I expect these nodes are still scanning.
> 
> ```
> # -- excludeNodes comma-separated node labels that the node-collector job should exclude from scanning (example kubernetes.io/arch=arm64,team=dev)
>   excludeNodes:
> ```

the reason the pod hang on `Pending state` it because it is not schedule to a Node from some reason

**Comment by ledroide** [comment]
> the reason the pod hang on `Pending state` it because it is not schedule to a Node from some reason

The job tries to schedule pods on control_plane servers, which have NoSchedule taint. This is the issue to fix.
* if we want _Node collector_ pods to be scheduled on control_plane, so we need a toleration in the podSpec to tolerate the NoSchedule taint
* if we don't want, so we must not generate pods with "Node-Selectors" that lead to schedule on control_plane.

**Comment by chary1112004** [comment]
> > @chen-keinan I see this property exclude nodes from scanning by label however I expect these nodes are still scanning.
> > ```
> > # -- excludeNodes comma-separated node labels that the node-collector job should exclude from scanning (example kubernetes.io/arch=arm64,team=dev)
> >   excludeNodes:
> > ```
> 
> the reason the pod hang on `Pending state` it because it is not schedule to a Node from some reason

@chen-keinan we have some nodes that could any pod (no need config toleration) locate. Could you reproduce this case?

**Comment by chen-keinan** [comment]
It is on prem or cloud ? I can give it a try but I do not recall such issue on my env.

**Comment by chary1112004** [comment]
@chen-keinan yes, it is on cloud. We are using eks (aws).

**Comment by ledroide** [comment]
> It is on prem or cloud ? I can give it a try but I do not recall such issue on my env.

On cloud too, with "vanila" kubeadm installations - almost similar to on-premise clusters. 
Control_plane  servers are tainted NoSchedule, and they host also the etcd cluster.
It's no fancy, by the way.

**Comment by chen-keinan** [comment]
> > It is on prem or cloud ? I can give it a try but I do not recall such issue on my env.
> 
> On cloud too, with "vanila" kubeadm installations - almost similar to on-premise clusters. Control_plane servers are tainted NoSchedule, and they host also the etcd cluster. It's no fancy, by the way.

@ledroide thanks for the input @chary1112004 do you want to try it ?

**Comment by chary1112004** [comment]
> > > It is on prem or cloud ? I can give it a try but I do not recall such issue on my env.
> > 
> > 
> > On cloud too, with "vanila" kubeadm installations - almost similar to on-premise clusters. Control_plane servers are tainted NoSchedule, and they host also the etcd cluster. It's no fancy, by the way.
> 
> @ledroide thanks for the input @chary1112004 do you want to try it ?

@chen-keinan from our side, we no need manage kubeadm as it is managed by aws. So it is not in our case. I understand that @ledroide describe about the environment that is facing the issue, not solution.

**Comment by chen-keinan** [comment]
> > > > It is on prem or cloud ? I can give it a try but I do not recall such issue on my env.
> > > 
> > > 
> > > On cloud too, with "vanila" kubeadm installations - almost similar to on-premise clusters. Control_plane servers are tainted NoSchedule, and they host also the etcd cluster. It's no fancy, by the way.
> > 
> > 
> > @ledroide thanks for the input @chary1112004 do you want to try it ?
> 
> @chen-keinan from our side, we no manage kubeadm as it is managed by aws. So it is not in our case. I understand that @ledroide describe about the environment that is facing the issue, not solution.

@chary1112004 I think he suggested to add toleration in nodeSpec for `NoSchedule taint` but if it doesn't work for you then need to understand why `node-collector` pods are pending for this specific Nodes

**Comment by chary1112004** [comment]
@chen-keinan After checking then it relates to node selector even I added all tolerations needed

...
nodeSelector:
    kubernetes.io/hostname: ip-192-168-120-211.eu-central-1.compute.internal
...

message: '0/x nodes are available: x node(s) didn''t match Pod''s node affinity/selector.

Could we disable node selector for pod node-collector?

**Comment by chen-keinan** [comment]
@chary1112004 if you disable this [flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L83) , node-collector will not be triggered

**Comment by chary1112004** [comment]
> @chary1112004 if you disable this [flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L83) , node-collector will not be triggered

Yes, I saw it in some threads to disable this one, actually could you please give summarize what purpose of node-collector then we could disable it for now. Thanks!

**Comment by chary1112004** [comment]
> @chen-keinan After checking then it relates to node selector even I added all tolerations needed Here is yaml pod node-collector:
> 
> ```
> ...
> nodeSelector:
>     kubernetes.io/hostname: <ip>.<region>.compute.internal
> ...
> ```
> 
> message: '0/x nodes are available: x node(s) didn''t match Pod''s node affinity/selector.
> 
> Could we disable node selector for pod node-collector?

So it is useful information for enable infra assessment.
Base on message of pod then I have checked again node affinity & node selector that is configured in pod node-collector.
- affinity: no config
- node selector:
```
nodeSelector:
    kubernetes.io/hostname: <ip>.<region>.compute.internal
```
 I have taken a look in default value file & all helm chart however there is no config for nodeSelector in value file then it may be generated from somewhere else. Then could we have option to disable nodeSelector in pod node-collector?

Thanks!

**Comment by chen-keinan** [comment]
> > @chen-keinan After checking then it relates to node selector even I added all tolerations needed Here is yaml pod node-collector:
> > ```
> > ...
> > nodeSelector:
> >     kubernetes.io/hostname: <ip>.<region>.compute.internal
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > message: '0/x nodes are available: x node(s) didn''t match Pod''s node affinity/selector.
> > Could we disable node selector for pod node-collector?
> 
> So it is useful information for enable infra assessment. Base on message of pod then I have checked again node affinity & node selector that is configured in pod node-collector.
> 
> * affinity: no config
> * node selector:
> 
> ```
> nodeSelector:
>     kubernetes.io/hostname: <ip>.<region>.compute.internal
> ```
> 
> I have taken a look in default value file & all helm chart however there is config empty setting for nodeSelector (nodeSelector: {}) in value file then it may be generated from somewhere else. Then could we have option to disable nodeSelector in pod node-collector?
> 
> Thanks!

it possible could be very easy change unless you want it to scan every node

**Comment by chary1112004** [comment]
@chen-keinan I understand this merge request is merged and node selector should be removed already then we do not need disable infra assessment or does it need any additional config that I need to update? Thanks!

**Comment by chen-keinan** [comment]
> @chen-keinan I understand this merge request is merged and node selector should be removed already then we do not need disable infra assessment or does it need any additional config that I need to update? Thanks!

OK , do you mind opening issue for it ?

**Comment by chary1112004** [comment]
> > @chen-keinan I understand this merge request is merged and node selector should be removed already then we do not need disable infra assessment or does it need any additional config that I need to update? Thanks!
> 
> OK , do you mind opening issue for it ?

Yes, I will open issue for this.

**Comment by ledroide** [comment]
Does it mean hopefully that v0.18.2 will fix the issue so I can set back `OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED="true"` ?

**Comment by chen-keinan** [comment]
> Does it mean hopefully that v0.18.2 will fix the issue so I can set back `OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED="true"` ?

I'll be adding a config flag to choose if to use `nodeSelector` or not

**Comment by chary1112004** [comment]
> > @chen-keinan I understand this merge request is merged and node selector should be removed already then we do not need disable infra assessment or does it need any additional config that I need to update? Thanks!
> 
> OK , do you mind opening issue for it ?

I create the ticket https://github.com/aquasecurity/trivy-operator/issues/1779
Thanks!

**Pull request merged**
