### PR TITLE
adding mage support

### LINKED ISSUE #1241: replace make file with mage
it is required to replace `make` with [mage](https://github.com/magefile/mage) to make `ci` workflow more flexible

### PR DESCRIPTION
**Pull request by sbdtu5498**
## Related issues
- Close #1241 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by sbdtu5498** [comment]
cc: @chen-keinan

**Comment by chen-keinan** [comment]
@sbdtu5498 thank you for the contribution, look like a very good start. couple of comments:
- it will be great to use [namespaces](https://github.com/aquasecurity/trivy/blob/main/magefiles/magefile.go#L172)
- it is required to updated [contribution guide](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md)
- update [github actions](https://github.com/aquasecurity/trivy-operator/tree/main/.github/workflows) relevant places 

it ok also to make the above changes in a separate PR, let me know what you decide

**Comment by chen-keinan** [comment]
@sbdtu5498 any update ?

**Comment by sbdtu5498** [comment]
@chen-keinan Sir, I will take a look at the prescribed changes and will push them in the upcoming week. The changes that needs to be made directly into the magefile I will force push them in this PR, but for others such as updating GitHub actions, and removing Makefile, if it feels right to do so, I will do it in another PR as it makes more sense.

**Comment by sbdtu5498** [comment]
@chen-keinan Sir, First of all, Sorry for the delays. I was a bit busy and about to take a look at the prescribed changes. I will take a look on them will push before wednesday. The changes that needs to be made directly into the magefile I will force push them in this PR, but for others such as updating GitHub actions, and removing Makefile, if it feels right to do so, I will do it in another PR as it makes more sense.

**Comment by chen-keinan** [comment]
@sbdtu5498 I really want to see this change merged to upstream. I hope you'll have some time to complete it :)

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
