### PR TITLE
Update trivy-operator.yaml

### PR DESCRIPTION
**Pull request by rewanthtammana**
## Description

```bash
kubectl apply -f https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.7.1/deploy/static/trivy-operator.yaml
```

image

In the [trivy-operator.yaml](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/static/trivy-operator.yaml), the after the creation of CRDs, the namespace must be created on the cluster. Instead in the current configuration, the namespace is created in the last leading to `namespaces "trivy-system" not found` error. This PR fixes the above error by creating the namespace first.

### CODE REVIEW

**Comment by chen-keinan** [comment]
@rewanthtammana  thanks you for the contribution , one comment

The static files are controlled by the [update static script](https://github.com/aquasecurity/trivy-operator/blob/main/hack/update-static.yaml.sh) the best will be to update the script and execute it to generate the correct static files

**Comment by rewanthtammana** [comment]
@chen-keinan Please have a look now

**Comment by chen-keinan** [comment]
> @chen-keinan Please have a look now

please check , [verify_generate script](https://github.com/aquasecurity/trivy-operator/blob/main/hack/verify-generated.sh) is failing

**Comment by chen-keinan** [comment]
@rewanthtammana are you still working on it ?

**Comment by rewanthtammana** [comment]
Yes, @chen-keinan

**Comment by chen-keinan** [comment]
thank you for the contribution lgtm 🚀

**Pull request merged**
