### PR TITLE
Add metrics about CVE vulnerability ID

### LINKED ISSUE #562: Add metrics about CVE vulnerability ID
Currently operator exposed metrics about VulnerabilityReport.
That's a good thing, but there is nothing about CVE. 

I propose to add metrics `trivy_vulnerability_id` which is a sensibly the same as current `trivy_image_vulnerabilities` but with the label `vuln_id` which permit to build dashboard focused en CVE, and made simple prometheus queries to search specific CVE in whole cluster.

In the past we have build something like that based on starboard with a json exporter, but this was hard to maintain and scale. Integrate this feature in operator metrics seems for me to be a good idea.

### PR DESCRIPTION
**Pull request by MatthieuFin**
## Description
This is a proposition about feature request [562](https://github.com/aquasecurity/trivy-operator/issues/562).

Which permit to expose new metrics (enable by default but disabled via operator env variable) about CVE vulnerabilities find in VulnerabilityReports

## Related issues
- Close #562

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@MatthieuFin this change could be a nice addition to `trivy-operator` metrics capability, however I agree with @JAORMX about the impact of metrics cardinality , I would suggest to make it `metricsVulnIdEnabled` disabled by default until we gather enough feedback on it usage.

**Comment by MatthieuFin** [comment]
Hi, yes i'm agree with that too !
ok to set it disabled by default, it will avoid bad surprise on upgrade.

But i have no really good workaround on this issue.
We could perhaps record only CVE with a minimum severity. Or reduce number of label maybe set it as configurable. By example we could only keep namespaces and not image repo / name / version.

**Comment by chen-keinan** [comment]
LGTM 🚀  thank you for the contribution

**Review by chen-keinan — APPROVED** [review]

**Comment by cebidhem** [comment]
I was looking for this, but reading the legit concerns I'd like to know if any of you had feedbacks on whether or not cardinality proved to be an issue with this enabled ?

**Pull request merged**
