### PR TITLE
fix: Updates ignorePolicy comments in values.yaml

### LINKED ISSUE #1986: error failed to apply the ignorePolicy
trivvy-operator logs following error messages:

filter error: filtering error: unable to filter vulnerabilities: failed to apply the policy: unable to prepare for eval: 1 error occurred: trivy.rego:0: rego_parse_error: empty module

I expect ignoPolicicy config from values file apply via configMap on scan jobs. It did work before.

Scan jobs pods being OOMKilled.

**Environment:**

- Trivy-Operator version: 0.19.3
- trivy-operator helm chart version: 0.21.3
- Kubernetes version: v1.28.5
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): AKSUbuntu-2204

### PR DESCRIPTION
**Pull request by KateFiroozi**
## Related issues
- Close #1986

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@KateFiroozi can you please sign the CLA

**Comment by KateFiroozi** [comment]
> @KateFiroozi can you please sign the CLA

should have been done

**Comment by KateFiroozi** [comment]
> @KateFiroozi workflow is blocked by CLA signup, please re-check if CLA is signed

Have done it multiple times.

**Comment by chen-keinan** [comment]
@KateFiroozi I'll pass it. thanks for the contribution 🚀

**Pull request merged**
