### PR TITLE
fix: appVersion version 0.10.1 into 0.10.2

### PR DESCRIPTION
**Pull request by fengshunli**
Signed-off-by: fengshunli <1171313930@qq.com>

## Related issues
- Close #XXX

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@fengshunli `v0.10.2` is a [helm release only](https://github.com/aquasecurity/trivy-operator/releases/tag/v0.10.2) therefore the `appVersion` is still on `v0.10.1`

later on this week we are planning to cut `v.0.11.0` which will include all latest code changes.

**Comment by fengshunli** [comment]
> @fengshunli `v0.10.2` is a [helm release only](https://github.com/aquasecurity/trivy-operator/releases/tag/v0.10.2) therefore the `appVersion` is still on `v0.10.1`
> 
> later on this week we are planning to cut `v.0.11.0` which will include all latest code changes.

@chen-keinan I modified some configuration

**Comment by chen-keinan** [comment]
> 
> @chen-keinan I modified some configuration

Can you please elaborate , not sure I understand which configuration

**Comment by fengshunli** [comment]
> > @chen-keinan I modified some configuration
> 
> Can you please elaborate , not sure I understand which configuration

v0.10.1 upgrade to v0.10.2 related configuration

**Comment by fengshunli** [comment]
Note Formatting Issues

**Comment by chen-keinan** [comment]
> 
> v0.10.1 upgrade to v0.10.2 related configuration

saw it and thats why I comment that v0.10.2 is helm release (only helm chart changes) , it should not include app changes , therefore we are not changing the appVersion.

The latest app changes will be released later on this week with  v0.11.0 , so `appVersion` will become `v0.11.0` on next release.

**Comment by fengshunli** [comment]
> > v0.10.1 upgrade to v0.10.2 related configuration
> 
> saw it and thats why I comment that v0.10.2 is helm release (only helm chart changes) , it should not include app changes , therefore we are not changing the `appVersion`
> 
> The latest app changes will be released later on this week with `v0.11.0` , so `appVersion` will become `v0.11.0` on next release.

ok

**Comment by chen-keinan** [comment]
@fengshunli I assume we can close this PR , `trivy-operator` is in version v0.11.0. wdyt ?

**Comment by fengshunli** [comment]
> @fengshunli I assume we can close this PR , `trivy-operator` is in version v0.11.0. wdyt ?

ok

**Comment by chen-keinan** [comment]
Closing , chart update with v0.11.0

**Pull request closed without merging**
