### PR TITLE
Fix helm chart configurations and readme

### LINKED ISSUE #1078: clusterComplaince and infraAssessement report activated by default
**What steps did you take and what happened:**

Even after disabling the clusterComplaince and infraAssessement with
```
# clusterComplianceEnabled the flag to enable cluster compliance report generation
  clusterComplianceEnabled: false
# infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: false
```

the logs still showing that there is an error with that:
```
{"level":"error","ts":"2023-03-20T12:39:41Z","logger":"reconciler.clustercompliancereport","msg":"failed to generate compliance report","compliance report":"/nsa","error":"no matches for kind \"ClusterInfraAssessmentReport\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/compliance.(*ClusterComplianceReportReconciler).generateComplianceReport.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/compliance/clustercompliancereport.go:68\nk8s.io/client-go/util/retry.OnError.func1\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/util/retry/util.go:51\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:222\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:228\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:423\nk8s.io/client-go/util/retry.OnError\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/util/retry/util.go:50\nk8s.io/client-go/util/retry.RetryOnConflict\n\t/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/util/retry/util.go:104\ngithub.com/aquasecurity/trivy-operator/pkg/compliance.(*ClusterComplianceReportReconciler).generateComplianceReport\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/compliance/clustercompliancereport.go:50\ngithub.com/aquasecurity/trivy-operator/pkg/compliance.(*ClusterComplianceReportReconciler).reconcileComplianceReport.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/compliance/clustercompliancereport.go:44\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235"}
```

**What did you expect to happen:**

**Anything else you would like to add:**

**Environment:**

- Trivy-Operator version 0.12.1
- Kubernetes version: 1.23.15

### PR DESCRIPTION
**Pull request by VF-mbrauer**
## Description

Added the missing Helm-Chart configuration directive as well as updated the readme.

- Close #1078

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@VF-mbrauer PR is looking good, do you mind updating the [configuration docs](https://github.com/aquasecurity/trivy-operator/blob/main/docs/getting-started/installation/configuration.md) as well.

you'll have to run `make generate-all` and commit changes in order to fix the `Verify code` check

**Comment by VF-mbrauer** [comment]
@chen-keinan Please check. Done.

**Comment by chen-keinan** [comment]
lgtm 🚀

**Comment by VF-mbrauer** [comment]
@chen-keinan also done!

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
