### PR TITLE
feat: mark old report for deletion

### LINKED ISSUE #237: vulnerabilityScannerScanOnlyCurrentRevisions does not delete old reports
**What steps did you take and what happened:**

* Enable vulnerabilityScannerScanOnlyCurrentRevisions on starboard operator
* See reports generated only for most current deployments
* Deploy new revision of deployment
* See report generated for new deployment
* See old report is still there

**What did you expect to happen:**

* old report being deleted as I only want reports for the current deployments

**Anything else you would like to add:**

* The implementation in #870 simply didn't add that part of the feature

**Environment:**

- Starboard version (use `starboard version`): `0.14.0`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
```
> sw_vers
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```

### PR DESCRIPTION
**Pull request by chen-keinan**
Signed-off-by: chenk <hen.keinan@gmail.com>

## Description
Mark Old reports for deletion

## Related issues
- Close #237 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by jrhunger** [comment]
Not sure what is the right place to ask this, but since this is included in v0.5.0-rc, should we expect existing vulnerabilityreports for inactive ReplicaSets to be deleted after upgrading from v0.4.0?

**Comment by chen-keinan** [comment]
> Not sure what is the right place to ask this, but since this is included in v0.5.0-rc, should we expect existing vulnerabilityreports for inactive ReplicaSets to be deleted after upgrading from v0.4.0?

The old reports are connected to old ReplicatSet with ownership of ownership , meaning as long the ReplicaSet exist the report related to it. will exist. (this is how it worked so far)

for you question is Yes , if the old replicaSet (what holding the report ) is exist in the cluster , then yes `trivy-oerator` will delete the old reports associated to it after upgrade.

**Comment by jrhunger** [comment]
I'm not seeing that happen in my cluster.  Is there anything i can do to drill into it further?
```
## vulnerabilityreports:
replicaset-fstore-svc-5d5b8d5f5b-change-certs-ownership   library/alpine                       3.6                   Trivy     8d
replicaset-fstore-svc-5d5b8d5f5b-fstore-svc               ##REDACTED##fstore.api     91                    Trivy     8d
replicaset-fstore-svc-6795d87bf8-change-certs-ownership   library/alpine                       3.6                   Trivy     8d
replicaset-fstore-svc-6795d87bf8-fstore-svc               ##REDACTED##fstore.api     90                    Trivy     8d
replicaset-fstore-svc-786c7596cd-change-certs-ownership   library/alpine                       3.6                   Trivy     10d
replicaset-fstore-svc-786c7596cd-fstore-svc               ##REDACTED##fstore.api     89                    Trivy     10d

## replicasets:
fstore-svc-5d5b8d5f5b   1         1         1       8d
fstore-svc-6795d87bf8   0         0         0       8d
fstore-svc-786c7596cd   0         0         0       10d
```
I have it in logDevMode and here are the logs related to this replicaset:
```
1.6669901729020205e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b-fstore-svc"}
1.6669901729028366e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b-change-certs-ownership"}
1.6669901729037666e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd-fstore-svc"}
1.6669901729046032e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8-change-certs-ownership"}
1.6669901729054308e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd-change-certs-ownership"}
1.6669901729055698e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8-fstore-svc"}
1.6669901729954715e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd-fstore-svc"}
1.6669901729993875e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8"}
1.6669901730000107e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b-fstore-svc"}
1.6669901730033557e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8-fstore-svc"}
1.6669901730033886e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b-change-certs-ownership"}
1.6669901730035868e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8-change-certs-ownership"}
1.6669901730037436e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd-change-certs-ownership"}
1.6669901730052307e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b"}
1.6669901730112195e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd"}
1.666990173016883e+09   DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "Pod", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b-fgvpg"}
1.6669901730169404e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring managed pod    {"kind": "Pod", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b-fgvpg", "controllerKind": "ReplicaSet", "controllerName": "fstore-svc-5d5b8d5f5b"}
1.66699017309757e+09    DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd"}
1.6669901730976834e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd", "name": "fstore-svc-786c7596cd"}
1.6669901731021032e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8"}
1.6669901731021705e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8", "name": "fstore-svc-6795d87bf8"}
1.6669901731113772e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.66699017311232e+09    DEBUG   reconciler.vulnerabilityreport  VulnerabilityReports already exist      {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b", "podSpecHash": "6f8ff96598"}
1.6669901752122753e+09  DEBUG   resourcecontroller      Ignoring managed pod    {"kind": "Pod", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b-fgvpg", "controllerKind": "ReplicaSet", "controllerName": "fstore-svc-5d5b8d5f5b"}
1.6669901856600301e+09  DEBUG   resourcecontroller      Checking whether configuration audit report exists      {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.6669901856602144e+09  DEBUG   resourcecontroller      Configuration audit report exists       {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.6669901934566617e+09  DEBUG   resourcecontroller      Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd", "name": "fstore-svc-786c7596cd"}
1.6669902064563658e+09  DEBUG   resourcecontroller      Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8", "name": "fstore-svc-6795d87bf8"}
1.6670553342955692e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd"}
1.6670553342956498e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd", "name": "fstore-svc-786c7596cd"}
1.6670553343237128e+09  DEBUG   resourcecontroller      Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd", "name": "fstore-svc-786c7596cd"}
1.6670553343965352e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8"}
1.6670553343965926e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8", "name": "fstore-svc-6795d87bf8"}
1.6670553351151984e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.6670553351166973e+09  DEBUG   reconciler.vulnerabilityreport  VulnerabilityReports already exist      {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b", "podSpecHash": "6f8ff96598"}
1.6670553356554966e+09  DEBUG   resourcecontroller      Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8", "name": "fstore-svc-6795d87bf8"}
1.6670553367090638e+09  DEBUG   resourcecontroller      Checking whether configuration audit report exists      {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.6670553367091844e+09  DEBUG   resourcecontroller      Configuration audit report exists       {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.6670557455974007e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8-fstore-svc"}
1.6670557455975108e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8"}
1.6670557455975754e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8", "name": "fstore-svc-6795d87bf8"}
1.667055745609041e+09   DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b-fstore-svc"}
1.6670557456098444e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-5d5b8d5f5b-change-certs-ownership"}
1.667055745612856e+09   DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd-fstore-svc"}
1.6670557456137605e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-6795d87bf8-change-certs-ownership"}
1.6670557456141016e+09  DEBUG   reconciler.ttlreport    Ignoring report without TTL set {"report": "##NAMESPACE##/replicaset-fstore-svc-786c7596cd-change-certs-ownership"}
1.6670557456165822e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b"}
1.667055745618045e+09   DEBUG   reconciler.vulnerabilityreport  VulnerabilityReports already exist      {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-5d5b8d5f5b", "podSpecHash": "6f8ff96598"}
1.667055745624392e+09   DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd"}
1.6670557456244373e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-786c7596cd", "name": "fstore-svc-786c7596cd"}
1.6670557456280558e+09  DEBUG   reconciler.vulnerabilityreport  Getting workload from cache     {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8"}
1.6670557456280987e+09  DEBUG   reconciler.vulnerabilityreport  Ignoring ReplicaSet with no active pods {"kind": "ReplicaSet", "name": "##NAMESPACE##/fstore-svc-6795d87bf8", "name": "fstore-svc-6795d87bf8"}
```

Hmm.. now that i paste that i think i see the issue. It says "Ignoring report without TTL set".  So i guess that means it will only delete old reports that were created after the TTL was enabled?

**Comment by jrhunger** [comment]
Easy enough to delete all the old ones that have no TTL annotation...
I generated commands for it like this.  Thanks for implementing this!!!

kubectl get vulnerabilityreport -o json -A | jq '.items[].metadata | select(.annotations == null)' | jq '{name:.name,namespace:.namespace}' | jq '"kubectl -n "+(.namespace)+" delete vulnerabilityreport "+(.name)'

**Pull request merged**
