### PR TITLE
feat: Enable passing values for operator through custom ConfigMap and/or Secrets

### LINKED ISSUE #1737: [Feature Request] Enable passing ENV variables via Secret or ConfigMap
Currently, most of the configuration OPTIONS, that can be configured via environment variables, need to be passed as Helm Values. See the [deploment.yaml](https://github.com/aquasecurity/trivy-operator/blob/67a005d83069dcc759f37b9f9b111ed92c10fb84/deploy/helm/templates/deployment.yaml#L35-L129) 

There are cases, where these configurations might not be hardcoded as Helm Values but rather passed located in Kubernetes Secrets and/or ConfigMaps.
Currently, there is no way to refer to ConfigMaps/Secrets to get the configuration for the Trivy-Operator Helm Chart. 

Kubernetes itself does support setting environment variables both 
- for [Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data)
- and for [ConfigMaps](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data)

And it is a widely used pattern. 
Should be technically not difficult to enable such a pattern with a priority like:

1. Use value from Helm Value if set
2. Use value from ConfigMap if set (and override Helm Value)
3. Use value from Secret if set (and override both Helm Value and ConfigMap)

cheers
flash ⚡

### PR DESCRIPTION
**Pull request by flash-me**
## Description

This feature / change enables providing Configuration for the Trivy-Operator from custom ConfigMap and/or Secret using the Helm Chart, which is a common / widely used pattern.

So far, all configuration have been passed using the `env` field in the [deployment](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/deployment.yaml#L46-L129).
Since this method has the [highest precedence](https://renehernandez.io/notes/env-vars-precedence-k8s-pod/), it was not possible to provide additional values.
To overcome this, all `.Values.operator.*` Helm values have been moved into their own ConfigMap called `trivy-operator-config` and then referred to it with `envFrom`.

This allowes to provide additional ConfigMaps/Secrets and override previous values.
The behaviour is defined in the [Container v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#container-v1-core) Spec of Kubernetes for the `envFrom` field:

> _[..] When a key exists in multiple sources, **the value associated with the last source will take precedence**. [..]_

The next Step was to add two additional Helm values, `.Values.operator.valuesFromSecret` and `.Values.operator.valuesFromConfigMap`. 
If defined, the deployment will apply values from the defined ConfigMap/Secret, while considering the following precedeence:

- `valuesFromConfigMap` will override `trivy-operator-config`
- `valuesFromSecret` will override `trivy-operator-config` AND `valuesFromConfigMap`

## How was it tested

I first deployed the Helm Chart with only the default values and then grabbed the env Variables of the `trivy-operator`, saving the output to a file:

```shell
kubectl -n trivy-system exec deployments/trivy-operator -- printenv \
  | grep OPERATOR \
  | sort \
  > envs_default.yaml
```

Then I moved all the `OPERATOR_*` values to the `trivy-operator-config` ConfigMap and again grabbed all the env Variables into a file `envs_cm.yaml`.

Now I compared the two files with `diff envs_default.yaml envs_cm.yaml`.
I used this approach for further use cases:

#### No breaking changes

Define Helm values 
```helm
operator:
  infraAssessmentScannerEnabled: false
  configAuditScannerEnabled: false
  webhookBroadcastTimeout: 33s
```

and expect them to be correctly applied, having the same behaviour as before:
```shell
OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED=false
OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED=false
OPERATOR_WEBHOOK_BROADCAST_TIMEOUT=33s
```

#### Custom ConfigMap overrides Helm values

Same Helm values as above + setting `valuesFromConfigMap` to `custom-operator-config`.
Deploy a custom ConfigMap  with content:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-operator-config
  namespace: trivy-system
data:
  OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED: "true"
  OPERATOR_WEBHOOK_BROADCAST_TIMEOUT: "22s"
```

check env Variables in the Pod:
```shell
OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED=false
OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED=true
OPERATOR_WEBHOOK_BROADCAST_TIMEOUT=22s
```

#### Custom Secret overrides Helm values AND custom ConfigMap

Same Helm values and ConfigMap as above + setting `valuesFromSecret` to `custom-operator-config`
Deploy a custom Secret with content:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: custom-operator-config
  namespace: trivy-system
type: Opaque
data:
  OPERATOR_WEBHOOK_BROADCAST_TIMEOUT: MTFz // '11s' encoded with base64
```

check env Variables in the Pod:
```shell
OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED=false
OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED=true
OPERATOR_WEBHOOK_BROADCAST_TIMEOUT=11s
```

## Related issues
- Close #1737

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by flash-me** [comment]
@chen-keinan I have troubles running `go run mage.go generate:manifests` while `go run mage.go generate:docs` works fine.

Do I miss something? 

<details>
<summary> Error output </summary>

```shell
go run mage.go generate:manifests
Generating CRDs and updating static YAML...
Creating LOCALBIN directory...
Downloading controller-gen...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0115e]

goroutine 30 [running]:
go/types.(*Checker).handleBailout(0xc0001a2400, 0xc000571d40)
        /usr/local/go/src/go/types/check.go:367 +0x88
panic({0xbb2600?, 0x128ad00?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xda56b8, 0x12935e0})
        /usr/local/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xda56b8?, 0x12935e0?})
        /usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdab9d8, 0x125f5e0}, 0xc0001a2400, 0x12935e0, 0xc00056eed8)
        /usr/local/go/src/go/types/const.go:106 +0x2c7
go/types.(*Checker).representation(0xc0001a2400, 0xc001087500, 0x12935e0)
        /usr/local/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).representable(0xc0001a2400, 0xc001087500, 0x12935e0)
        /usr/local/go/src/go/types/const.go:239 +0x26
go/types.(*Checker).shift(0xc0001a2400, 0xc0010874c0, 0xc001087500, {0xda97d8, 0xc000376300}, 0x14)
        /usr/local/go/src/go/types/expr.go:650 +0x1eb
go/types.(*Checker).binary(0xc0001a2400, 0xc0010874c0, {0xda97d8, 0xc000376300}, {0xda9ce8, 0xc0002d0500}, {0xda9ce8, 0xc0002d0520}, 0x14, 0x3f942)
        /usr/local/go/src/go/types/expr.go:796 +0x150
go/types.(*Checker).exprInternal(0xc0001a2400, 0x0, 0xc0010874c0, {0xda97d8, 0xc000376300}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x206
go/types.(*Checker).rawExpr(0xc0001a2400, 0x0, 0xc0010874c0, {0xda97d8?, 0xc000376300?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc0001a2400, 0x0?, 0xc0010874c0, {0xda97d8?, 0xc000376300?})
        /usr/local/go/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).constDecl(0xc0001a2400, 0xc000619aa0, {0x0, 0x0}, {0xda97d8, 0xc000376300}, 0x0)
        /usr/local/go/src/go/types/decl.go:488 +0x328
go/types.(*Checker).objDecl(0xc0001a2400, {0xdb1018, 0xc000619aa0}, 0x0)
        /usr/local/go/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).ident(0xc0001a2400, 0xc001087480, 0xc000531ee0, 0x0, 0x0)
        /usr/local/go/src/go/types/typexpr.go:62 +0x250
go/types.(*Checker).exprInternal(0xc0001a2400, 0x0, 0xc001087480, {0xda82d8, 0xc000531ee0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1033 +0x138
go/types.(*Checker).rawExpr(0xc0001a2400, 0x0, 0xc001087480, {0xda82d8?, 0xc000531ee0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc0001a2400, 0xc000570da0?, 0xc001087480, {0xda82d8?, 0xc000531ee0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).binary(0xc0001a2400, 0xc001087440, {0xda97d8, 0xc000373c80}, {0xda82d8, 0xc000531ec0}, {0xda82d8, 0xc000531ee0}, 0xc, 0x3f0c3)
        /usr/local/go/src/go/types/expr.go:784 +0xcc
go/types.(*Checker).exprInternal(0xc0001a2400, 0x0, 0xc001087440, {0xda97d8, 0xc000373c80}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x206
go/types.(*Checker).rawExpr(0xc0001a2400, 0x0, 0xc001087440, {0xda97d8?, 0xc000373c80?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc0001a2400, 0xc0008f7140?, 0xc001087440, {0xda97d8?, 0xc000373c80?})
        /usr/local/go/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).constDecl(0xc0001a2400, 0xc0008f7200, {0x0, 0x0}, {0xda97d8, 0xc000373c80}, 0x0)
        /usr/local/go/src/go/types/decl.go:488 +0x328
go/types.(*Checker).objDecl(0xc0001a2400, {0xdb1018, 0xc0008f7200}, 0x0)
        /usr/local/go/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc0001a2400)
        /usr/local/go/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc0001a2400, {0xc0008af2c0, 0xa, 0xa})
        /usr/local/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0003730b0, 0xc000459d80)
        /home/flash/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000459d80)
        /home/flash/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc000376d20, 0xc000459d80)
        /home/flash/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x4c?)
        /home/flash/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 70
        /home/flash/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:260 +0x1c5
Error: running "/home/flash/sources/trivy_contrib/trivy-operator/bin/controller-gen crd:allowDangerousTypes=true paths=./pkg/apis/... output:crd:artifacts:config=deploy/helm/crds" failed with exit code 2
exit status 2
```

</details>

**Comment by flash-me** [comment]
No idea whats going on in the Pipeline.
image

**Comment by chen-keinan** [comment]
@flash-me I have push a commit which update the static yaml file (`mage generate:all`)

**Review by chen-keinan — APPROVED** [review]
@flash-me lgtm 🚀  thanks for the contribution

**Pull request merged**
